// // import { Inter } from "next/font/google";
// import Header from "@/components/Header/Header";
// import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Header />
//         {children}
//       </body>
//     </html>
//   );
// }


import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";  // Import Footer
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="your-body-class">
        <Header />
        <main>{children}</main>
        <Footer />  {/* Add Footer here */}
      </body>
    </html>
  );
}
